<?php

include '../public/layouts/header.php';

?>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
<script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css">
<div class="container">  
                <h3 align="center"><?php  echo $data; ?> Data</h3>  
                <br />  
                <div class="table-responsive table-hover">  
                     <table id="employee_data" class="table table-striped table-bordered ">  
                          <thead>  
                               <?php
                                $x = 1;
                                foreach($data as $d){
                                    if($x == 1){
                                        printf("<tr><td>%s</td></tr>",implode('</td><td>',array_keys($d)));
                                        break;
                                    } }
                               ?>

                          </thead>  
                          <?php  
                          foreach($data as $d){
                            printf("<tr><td>%s</td></tr>",implode('</td><td>',$d));
                        } 
                          ?>  
                     </table>  
                </div>  
           </div>  
      </body>  
 </html>  
 <script>  
 $(document).ready(function(){  
      $('#employee_data').DataTable();
 });  
 </script>  
